export const websiteLinks = [
  'https://www.dextools.io/app/pancakeswap/pair-explorer/0x93d94fcb0dcc8a88257b2d2eec7a2615ebedb542',
  'https://coinmarketcap.com/currencies/everrise/',
  'https://www.coingecko.com/en/coins/everrise',
  'https://s.weibo.com/weibo/everrise?topnav=1&wvr=6&b=1',
  'https://bscscan.com/token/0xc7d43f2b51f44f09fbb8a691a0451e8ffcf36c0a',
  'https://www.reddit.com/r/EverRise/',
  'https://www.google.com/search?q=WWW.EVERRISECOIN.COM',
  'https://www.google.com/search?q=everrisecoin',
  'https://www.google.com/search?q=everrise',
  'https://www.youtube.com/results?search_query=everrise+token',
  'https://www.youtube.com/results?search_query=buy+everrise+token',
  'https://www.rugfreecoins.com/details/795',
  'https://www.certik.org/projects/everrise',
];
